{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base='ContentObjectAttribute' html_class='half'}
    <input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" class="box ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="text" name="{$attribute_base}_amicus_number_{$attribute.id}" size="10" value="{$attribute.data_int}" />    
    <input type="submit" title="Importa dati" name="FillBook" value="{'Importa dati'|i18n( 'extension/ocamicus' )}" />

{/default}

